### ISSUE TITLE
validation because user error, empty report

### ISSUE THREAD

**Issue by xvazquezc** [enasequence/webin-cli#17]
Hi,

I'm trying to submit an annotated genome but during validation it complains about duplicated assembly entries. The problem is that there is no report at all and all contigs in the assembly have unique names:

```
$ java -jar ~/webin-cli-1.8.5.jar -context genome -username username -password password -manifest test_isored-2.txt -outputdir ./ -validate
INFO : Your application version is 1.8.5
INFO : Creating report file: /home/xabi/Desktop/SBI_projects/miriam/data_submission/././webin-cli.report
ERROR: Submission validation failed because of a user error: Entry names are duplicated in assembly : ISORED2_1,ISORED2_10,ISORED2_11,ISORED2_12,ISORED2_13,ISORED2_14,ISORED2_15,ISORED2_16,ISORED2_17,ISORED2_18,ISORED2_19,ISORED2_2,ISORED2_20,ISORED2_21,ISORED2_22,ISORED2_23,ISORED2_24,ISORED2_25,ISORED2_26,ISORED2_27,ISORED2_28,ISORED2_29,ISORED2_3,ISORED2_30,ISORED2_31,ISORED2_32,ISORED2_33,ISORED2_34,ISORED2_35,ISORED2_36,ISORED2_37,ISORED2_38,ISORED2_39,ISORED2_4,ISORED2_40,ISORED2_41,ISORED2_42,ISORED2_43,ISORED2_44,ISORED2_45,ISORED2_46,ISORED2_47,ISORED2_48,ISORED2_49,ISORED2_5,ISORED2_50,ISORED2_51,ISORED2_52,ISORED2_53,ISORED2_54,ISORED2_55,ISORED2_56,ISORED2_57,ISORED2_6,ISORED2_7,ISORED2_8,ISORED2_9. Please check validation reports for further information: /home/xabi/Desktop/SBI_projects/miriam/data_submission/./genome/ISORED-2/validate
```

But there is no validation report produced at all so I don't know what's the exact problem.

If I try to validate it without the annotation file, there is no problem at all. The same goes if I run with `-context sequence` and validate the `.embl` file on its own.

Any idea about what can be wrong?

Thank you,
Xabi

**Comment by raskoleinonen** [comment]
Hi Xabi,

Could you please first try to submit using the latest Webin-CLI version:
https://github.com/enasequence/webin-cli/releases/tag/v1.8.7

If the problem still persists could you please upload the manifest file and the data files to your Webin upload folder (https://ena-docs.readthedocs.io/en/latest/fileprep/upload.html#upload-files) and we will investigate the error in full detail.

Best & Thank you,
Rasko

**Comment by xvazquezc** [comment]
Could you provide instructions for compiling the source code? There is no jar file available

**Comment by raskoleinonen** [comment]
My apologies, we will add the jar file shortly.

**Comment by raskoleinonen** [comment]
webin-cli-1.8.7.jar has been uploaded to https://github.com/enasequence/webin-cli/releases/tag/v1.8.7

**Comment by xvazquezc** [comment]
Thanks Rasko.

I tested it and I get the same result. I uploaded the manifest as well as the annotation and assembly files. Hopefully you can see anything I'm missing...

**Comment by raskoleinonen** [comment]
Thanks I can see the files. We will take a look shortly.

**Comment by xvazquezc** [comment]
Hi @raskoleinonen ,
Have you had a chance to take a look?
Thanks,

**Comment by raskoleinonen** [comment]
Unfortunately, not yet. @snathanvj will take a look as soon as he has finished adding support for author and address manifest fields in genome/transcriptome/sequence Webin-CLI contexts. This feature has been requested by several brokers and has been flagged as the highest priority by the ENA helpdesk. This work should be completed early next week.

**Comment by snathanvj** [comment]
Hi Xabi,
   Sorry for the delayed response. I have checked it, it seem like the fasta and flatfile has the same entry names. As the error message states , all these names or available in both flatfile (AC * line) and in fasta , so it is duplicate. I checked one entry randomly ISORED2_10 , it seems liek both the sequence are same, in such case you can submit either flatfile or fasta not both, if the sequence in both flatfile and fasta are difference then please change the entry names in any one of those files.

ERROR: Submission validation failed because of a user error: Entry names are duplicated in assembly : ISORED2_1,ISORED2_10,ISORED2_11,ISORED2_12,ISORED2_13,ISORED2_14,ISORED2_15,ISORED2_16,ISORED2_17,ISORED2_18,ISORED2_19,ISORED2_2,ISORED2_20,ISORED2_21,ISORED2_22,ISORED2_23,ISORED2_24,ISORED2_25,ISORED2_26,ISORED2_27,ISORED2_28,ISORED2_29,ISORED2_3,ISORED2_30,ISORED2_31,ISORED2_32,ISORED2_33,ISORED2_34,ISORED2_35,ISORED2_36,ISORED2_37,ISORED2_38,ISORED2_39,ISORED2_4,ISORED2_40,ISORED2_41,ISORED2_42,ISORED2_43,ISORED2_44,ISORED2_45,ISORED2_46,ISORED2_47,ISORED2_48,ISORED2_49,ISORED2_5,ISORED2_50,ISORED2_51,ISORED2_52,ISORED2_53,ISORED2_54,ISORED2_55,ISORED2_56,ISORED2_57,ISORED2_6,ISORED2_7,ISORED2_8,ISORED2_9

let me know if I did not understand something correctly or if you have any clarifications.
Thanks,
Senthil

**Comment by xvazquezc** [comment]
Hi @snathanvj ,

That's because the flatfile is the annotation of the fasta file. ~~Maybe I don't understand the instructions for uploading an annotated genome reconstructed from a metagenome. The allowed fields in the `-context sequence` manifest does not include some details usually deemed important for the assembly/genome information, e.g. coverage.~~

I re-read the docs and I think I got it clear now. Sorry for the inconvenience.

Thanks,
Xabi

**Comment by snathanvj** [comment]
Hi Xabi,
     Thanks for your response. annotation_only file should not contain sequence ,but you already have annotation and sequence in a file, I think you can just validate and submit that file alone.  Let me know if any clarification required, otherwise I will close this issue. 
Thanks,
Senthil
