### ISSUE TITLE
Read validator issue: Unable to determine pairing from set

### ISSUE THREAD

**Issue by holmrenser** [enasequence/webin-cli#27]
I am trying to submit single end 50bp transcriptome reads generated with a BGISEQ-500, but I run into the following validation error: 

```
INFO : Collected 23815623 reads [file: /mnt/scratch/holme003/parasponia/noot_samples/Reads/Clean/1/CL100110603_L2_WHPLAmxzRAAARAA-543_1.fq.gz]
INFO : Collected 3 read labels: [1, 2, /mnt/scratch/holme003/parasponia/noot_samples/Reads/Clean/1/CL100110603_L2_WHPLAmxzRAAARAA-543_1.fq.gz] [file: /mnt/scratch/holme003/parasponia/noot_samples/Reads/Clean/1/CL100110603_L2_WHPLAmxzRAAARAA-543_1.fq.gz]
INFO : Has possible duplicate(s): false [file: /mnt/scratch/holme003/parasponia/noot_samples/Reads/Clean/1/CL100110603_L2_WHPLAmxzRAAARAA-543_1.fq.gz]
ERROR: When submitting paired reads using two Fastq files the reads must follow Illumina paired read naming conventions. This was not the case for the submitted Fastq files: [Luk.ac.ebi.ena.readtools.webin.cli.rawreads.RawReadsFile;@75437611. Unable to determine pairing from set: 1,2,/mnt/scratch/holme003/parasponia/noot_samples/Reads/Clean/1/CL100110603_L2_WHPLAmxzRAAARAA-543_1.fq.gz
```

My manifest has only one `FASTQ` line, and the validator correctly only reads this one file. Any ideas where the `1` and `2` read labels are coming from?

**Comment by raskoleinonen** [comment]
Webin looks for paired reads also when submitting single FASTQ files. The logic used is the same as when submitting two FASTQ files except that the lookup is done within rather than between files. 

This functionality is historical and we have low thousands of submission of paired FASTQs submitted as single files. There has been a handful of problems like the one described here. I.e. an unhelpful error (in terms of being able to address the problem) when read pairing fails for single FASTQ files.

In the short term, the read names should be changed to overcome this problem. Unfortunately, I am not able to immediately advice how. The read name format, that relates to the read pairing logic, is described in:  https://ena-docs.readthedocs.io/en/latest/submit/fileprep/reads.html#fastq-format

In the long term, it would be better to remove read pairing functionality from single FASTQ files. Unfortunately, because of other priorities we have not had the opportunity to address this yet.

**Comment by holmrenser** [comment]
This is a very helpful pointer, I will try to change the FASTQ headers according to the provided documentation and see if this fixes the problem. Will report back here upon success/failure!

**Comment by holmrenser** [comment]
@raskoleinonen reporting back with a success: the BGISEQ-500 headers in my files are as follows: `@CL100110603L2C001R001_23`, so definitely not in the Casava1.8 format. Per the described read name format in the link you provided, adding `/1` at the end of each header fixed the issue.

If the read validator code is available on github somewhere I am willing to take a look and submit a PR to at least come up with a more descriptive error message.

**Comment by raskoleinonen** [comment]
This reply is long overdue but we have removed read pairing functionality for single Fastq submissions in Webin-CLI version 3.4.0 released today:

https://github.com/enasequence/webin-cli/releases/tag/v3.4.0

I hope this will prevent the submission problem you experienced in the future. Please let us know if this is not the case.

**Comment by holmrenser** [comment]
I'll be submitting some new data shortly, fingers crossed!
