### ISSUE TITLE
sequencing data submission

### ISSUE THREAD

**Issue by bynjh007** [enasequence/webin-cli#38]
Hi,

I have two questions.

First, I keep facing error when I am trying to upload my RNA-seq file with webin-cli tool. The data seems to be successfully validated according to the message, but I got the following error message:
--------
INFO : The submission has been validated successfully.
ERROR: Failed to upload files to webin.ebi.ac.uk using FTP. Connection timed out (Connection timed out) Failed to upload files to webin.ebi.ac.uk because of a system error.
--------

Second, should I make separate manifest file for each sample? would it be possible to generate one manifest file to contain all the samples that I want to submit?

Best,

**Comment by raskoleinonen** [comment]
Dear Colleague.

The first error is caused by Webin-CLI not being able to connect to webin2.ebi.ac.uk using FTPS. This may be a transient error that will resolve itself (e.g. a short-lived server-side problem) or there might be a problem with your local firewall not allowing FTPS traffic. The webin2.ebi.ac.uk server can be directly tested by connecting to it using FTPS with your Webin-N account as the user name.

As for the second question, the Webin-CLI is intentionally designed to accept only one manifest file at a time, in your case, only one RNA-seq file associated with one study and one sample. In many cases Webin-CLI is best used through dedicated workflow managers such as Nextflow or directly executed through a batch scheduler such as AWSBatch or LSF that allow Webin-CLI to be efficiently executed in large number of parallel sessions.

**Comment by raskoleinonen** [comment]
There is a new version of Webin-CLI with a slightly different FTPS configuration:

https://github.com/enasequence/webin-cli/releases/tag/v3.7.0

**Comment by raskoleinonen** [comment]
We have deployed Webin-CLI version 6.0.0 with build-in FTP(S)/Aspera/HTTPS call retries and improved logging of these errors:
https://github.com/enasequence/webin-cli/releases/tag/6.0.0

This may insulate users from transient errors and will help us to diagnose the exact problem from the logs. For example, each different type of FTP(S) error can be identified from the logs.

Please upgrade to Webin-CLI version 6.0.0 and if you have further file upload problems please contact us preferably using (fastest response time):
https://www.ebi.ac.uk/ena/browser/support
