### ISSUE TITLE
Uploading Large Datasets

### ISSUE THREAD

**Issue by chandni177** [enasequence/webin-cli#40]
Hello,
I am in the process of uploading a relatively large collection of datasets, where each fastq.gz file takes about 45 min to upload (between 1-2Gb) 
- Is this the speed you expect?
- Is it possible for me to upload multiple datasets simultaneously using the same ENA account?
- Is there a faster way to upload larger files?
Thank you!
Disclaimer : I realize I'm using version 3.4, so I will change to the newer version and see if that will speed things up

**Comment by raskoleinonen** [comment]
Dear Colleague,

Fastq file submission time is mostly about file validation and file upload. 

The file upload speed is primarily determined by the network connection between you and EBI's data centers and by the general load of EBI's network interfaces. One way to attempt to increase file upload speed is to install Aspera Cli and use the -ascp option in which case Aspera is used instead of FTPS.

Validation of Fastq files may take quite some time as by default all reads in the file are read through. We have added a -quick flag into the latest Webin-CLI release (https://github.com/enasequence/webin-cli/releases/tag/v3.5.0) that limits the Fastq file validation time to a fixed period (currently 5 minutes). Basically, it opens the Fastq file and validates as many reads as possible from the beginning of the file within the 5 minute time window. The downside of this is that the file is not completely checked and post-submission processing may fail for example if the gzip archive is corrupted at the end.

Webin-CLI has been designed to be executed in parallel using a job dispatcher of choice (e.g at EBI we would use for example LSF). Practically, one would write a script or program that creates a manifest file for each Fastq file to be submitted and executes Webin-CLI for each of these input manifest files using a job dispatcher. In theory, one could run tens or hundreds of these jobs in parallel. In practice, it is good to start with a lower number of parallel jobs and monitor the total network use not to overwhelm it locally or at EBI's end.

I hope you might find this information useful.

Best wishes,
Rasko Leinonen

**Comment by chandni177** [comment]
Ok, done all 3! The processing for a few that I observed has been taking longer than 5 minutes, but overall the submissions are much faster now. 
Thank you!
