### ISSUE TITLE
Genome assembly upload - ERROR: Failed to connect to webin.ebi.ac.uk using FTP

### ISSUE THREAD

**Issue by utritala** [enasequence/webin-cli#43]
Hello,
I am trying to upload a genome assembly to ENA using Webin-cli version 3.6.0. Here is my command: ` java -jar webin-cli-3.6.0.jar -submit -manifest=manifest.txt -username=xxxxxxx -password=xxxxxx -context=genome`. 
The validation is successful but it is failing to upload the files to ENA with the error: `ERROR: Failed to connect to webin.ebi.ac.uk using FTP. Failed to upload files to webin.ebi.ac.uk because of a system error.` I am able to login to ftp.webin.ebi.ac.uk with my usual webin credentials though.  Please could you help? 
Many thanks

**Comment by raskoleinonen** [comment]
The problem is possibly with the FTPS protocol that Webin-CLI uses instead of FTP: https://ena-docs.readthedocs.io/en/latest/submit/fileprep/upload.html#appendix-configuring-your-firewall-for-ena-upload

Could you please try of you can connect to webin.ebi.ac.uk using FTPS?

There is also a new version https://github.com/enasequence/webin-cli/releases/tag/v3.7.0 with a slightly different FTPS configuration.

**Comment by maxbranger** [comment]
Hi,
we just got the same error.

2021-03-23T17:11:25 INFO : Submission has not been validated previously.                                                                                                                       
2021-03-23T17:11:27 INFO : The submission has been validated successfully.                                                                                                                     
2021-03-23T17:11:27 ERROR: Failed to connect to webin.ebi.ac.uk using FTP. Failed to upload files to webin.ebi.ac.uk because of a system error.                                                
uk.ac.ebi.ena.webin.cli.WebinCliException: Failed to connect to webin.ebi.ac.uk using FTP. Failed to upload files to webin.ebi.ac.uk because of a system error.

We successfully try, with a collegue, to connect using ftp in command line and using Filezilla.
The error occured using Webin-CLI 3.7

Thanks for feedback,

**Comment by utritala** [comment]
Hi ,
Thanks for getting back to me.
I was advised by ENA helpdesk to use aspera (ascp) and that worked fine.
Cheers,
Urmi

**Comment by raskoleinonen** [comment]
We have deployed Webin-CLI version 6.0.0 with build-in FTP(S)/Aspera/HTTPS call retries and improved logging of these errors:
https://github.com/enasequence/webin-cli/releases/tag/6.0.0

This may insulate users from transient errors and will help us to diagnose the exact problem from the logs. For example, each different type of FTP(S) error can be identified from the logs.

Please upgrade to Webin-CLI version 6.0.0 and if you have further file upload problems please contact us preferably using (fastest response time):
https://www.ebi.ac.uk/ena/browser/support
