### ISSUE TITLE
FQ file does not exist in the upload area

### ISSUE THREAD

**Issue by sergioSEa** [enasequence/webin-cli#44]
Dear webin-cli staff,

I am attempting to upload a FQ pair using webin-cli-3.5.0.jar. My command is as follows:
> java -jar webin-cli-3.5.0.jar -userName XXXXX -password XXXXX -context reads -manifest Manifest.txt -ascp   -submit

I am using ascp because the FTP protocol was failing due to connection time out, however with Aspera it seems to work. 
Files  go through validation with no problem, and are successfully uploaded to webin2.ebi.ac.uk. However I get the following error:

> ERROR: In run, alias:"webin-reads-D30P", accession:"". File "webin-cli/reads/D30P/D30P_BDME190634188-1a_HTLKJDSXX_L2_1.fq.gz" does not exist in the upload area.In run, alias:"webin-reads-D30P", accession:"". File "webin-cli/reads/D30P/D30P_BDME190634188-1a_HTLKJDSXX_L2_2.fq.gz" does not exist in the upload area. The submission has failed because of a system error.

How am I meant to interpret this error and how should I attempt to troubleshoot it?

Thank you for your help.

**Comment by raskoleinonen** [comment]
The error suggests that the file being submitted has not been successfully uploaded. FTPS connection timeout may be caused by firewall setting: https://ena-docs.readthedocs.io/en/latest/submit/fileprep/upload.html#appendix-configuring-your-firewall-for-ena-upload. If you could contact the ENA helpdesk using https://www.ebi.ac.uk/ena/browser/support we may be able to assist further. For example, given your Webin submission account number we could check if any files have been successfully uploaded.

**Comment by raskoleinonen** [comment]
There is a new version of Webin-CLI with a slightly different FTPS configuration:
https://github.com/enasequence/webin-cli/releases/tag/v3.7.0

**Comment by raskoleinonen** [comment]
We have deployed Webin-CLI version 6.0.0 with build-in FTP(S)/Aspera/HTTPS call retries and improved logging of these errors:
https://github.com/enasequence/webin-cli/releases/tag/6.0.0

This may insulate users from transient errors and will help us to diagnose the exact problem from the logs. For example, each different type of FTP(S) error can be identified from the logs.

Please upgrade to Webin-CLI version 6.0.0 and if you have further file upload problems please contact us preferably using (fastest response time):
https://www.ebi.ac.uk/ena/browser/support
